# application.yml
--- 
spring: 
  application: 
    name: c-service
eureka: 
  client: 
    serviceUrl: 
#      defaultZone: http://localhost:8761/eureka/
   
        defaultZone: http://eureka:8761/eureka/
# leave eureka.instance.leaseRenewalIntervalInSeconds unchanged in production
# just here to provide quicker updates to Eureka for demos
 
server: 
# port: ${PORT:${SERVER_PORT:0}}
  port: 8080


---
spring: 
  profiles: Carlo
  application: 
    name: c-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    

  
--- 
spring: 
  profiles: Chiara
  application: 
    name: c-service
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

