package asw.a_service.c.domain;

import org.springframework.stereotype.Service;
import java.util.ArrayList;
import java.util.List;
import org.springframework.beans.factory.annotation.Value;


@Service
public class CService {
		
	@Value("${spring.profiles}")
	private String profile;
	
	private List<String> requests = new ArrayList<String>();

	public String saveRequest(String request) {
		this.requests.add(request);
		String creator = request.split(":")[0];
		String animal = request.split(":")[1];
		
		
		return "   \"" + animal + "\" generated by " + creator+ " | request  \"" + request  + "\" saved by -> " + profile;
		
		
	}
	
	public String getRequests() {
		return "  " +profile + ": " + this.requests.toString();
		
	}
	
	


	
	
}
